package th.mfu.service.test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.util.List;
import java.util.Map;

import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.Entity;
import javax.ws.rs.client.Invocation.Builder;
import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

/**
 * YOUR CHECKLIST FOR TODAY. Do not edit this file - make it pass.
 *
 * This is an INTEGRATION TEST. A unit test calls a Java method; this calls the
 * running service over a real HTTP connection, the way Postman does - through
 * Tomcat, through Jackson, into MySQL and back.
 *
 * Run it from the TOP folder:
 *
 *     mvn verify
 *
 * Maven starts the service, runs these tests against it, and stops it again.
 *
 * The name ends in IT, not Test, on purpose:
 *     surefire runs *Test  during  mvn test
 *     failsafe runs *IT    during  mvn verify
 * Rename it to *Test and it would run BEFORE the server starts, and every test
 * would fail with "Connection refused".
 *
 * EXPECT THESE TO FAIL AT THE START. They pass as you work through the steps:
 *
 *     testServiceIsUp                      step 1  (@EntityScan)
 *     testBookIsFlatOnTheWire              steps 2-4 (DTO + mapper + controller)
 *     testBookHidesTheEntityCollections    steps 2-4
 *     testCreateAcceptsTheDtoShape         step 4
 *     testPatchKeepsTheFieldsYouDidNotSend step 5   <- today's main idea
 *     testPatchUnknownBookIs404            step 5
 *
 * Notice this file never imports Book or BookDTO. It reads the JSON into a Map,
 * exactly like a real client would - it tests the CONTRACT, not our classes.
 */
public class BookResourceIT {

    private static final String BOOKS = "http://localhost:8080/api/books";

    private static Client client;

    @BeforeClass
    public static void createClient() {
        // Slide "Create Client": ClientBuilder makes a client that can open
        // connections to the web service.
        client = ClientBuilder.newClient();
    }

    @AfterClass
    public static void closeConnection() {
        client.close();
    }

    private Builder target(String uri) {
        return client.target(uri).request(MediaType.APPLICATION_JSON);
    }

    /** Step 1. Until @EntityScan is added, the service does not even start. */
    @Test
    public void testServiceIsUp() {
        try (Response response = target(BOOKS).get()) {
            assertEquals(Response.Status.OK.getStatusCode(), response.getStatus());

            List<Map<String, Object>> books = response.readEntity(
                    new GenericType<List<Map<String, Object>>>() {
                    });
            assertTrue("data.sql should have loaded 10 books", books.size() >= 10);
        }
    }

    /** Steps 2-4. The DTO is flat and renamed. */
    @Test
    public void testBookIsFlatOnTheWire() {
        Map<String, Object> book = getBook(10002L);

        assertEquals("1984", book.get("title"));

        // renamed by @JsonProperty
        assertTrue("expected publish-year in the JSON", book.containsKey("publish-year"));
        assertTrue("expected added-date in the JSON", book.containsKey("added-date"));

        // flattened: the category became two plain fields
        assertEquals("expected a flat category_id",
                10002, ((Number) book.get("category_id")).intValue());
        assertEquals("expected a flat category_name",
                "Science Fiction", book.get("category_name"));
    }

    /** Steps 2-4. What the DTO leaves out never travels. */
    @Test
    public void testBookHidesTheEntityCollections() {
        Map<String, Object> book = getBook(10002L);

        assertTrue("the nested category object should be gone - flatten it",
                !book.containsKey("category"));
        assertTrue("the entity's Java field name should not appear; use publish-year",
                !book.containsKey("year"));
        assertTrue("the entity's Java field name should not appear; use added-date",
                !book.containsKey("addedDate"));
    }

    /** Step 4. The client sends the DTO shape, with a flat category_id. */
    @Test
    public void testCreateAcceptsTheDtoShape() {
        Long id = createBook("Integration test book", "A Tester", 2026);
        Map<String, Object> created = getBook(id);

        assertEquals("Integration test book", created.get("title"));
        assertEquals("A Tester", created.get("author"));
        assertEquals(2026, ((Number) created.get("publish-year")).intValue());
        assertEquals("Fiction", created.get("category_name"));

        deleteBook(id);
    }

    /**
     * Step 5. TODAY'S MAIN IDEA.
     *
     * Only the title is sent. Everything else must survive, because the mapper
     * is set to nullValuePropertyMappingStrategy = IGNORE and the controller
     * loads the existing row before merging onto it.
     *
     * If this test wipes the author, you either forgot @BeanMapping(...IGNORE),
     * or a DTO field is a primitive (int) where it should be an object (Integer).
     */
    @Test
    public void testPatchKeepsTheFieldsYouDidNotSend() {
        Long id = createBook("Before the patch", "Kent Beck", 2002);

        try (Response response = client.target(BOOKS + "/" + id)
                .request(MediaType.APPLICATION_JSON)
                .method("PATCH", Entity.json("{\"title\":\"After the patch\"}"))) {

            assertEquals(Response.Status.OK.getStatusCode(), response.getStatus());
        }

        Map<String, Object> after = getBook(id);
        assertEquals("the title should have changed", "After the patch", after.get("title"));
        assertEquals("the author was NOT sent, so it must survive",
                "Kent Beck", after.get("author"));
        assertEquals("the year was NOT sent, so it must survive",
                2002, ((Number) after.get("publish-year")).intValue());
        assertNotNull("the added date was NOT sent, so it must survive",
                after.get("added-date"));
        assertEquals("the category was NOT sent, so it must survive",
                "Fiction", after.get("category_name"));

        deleteBook(id);
    }

    /** Step 5. An unknown id must still be a clean 404, not a 500. */
    @Test
    public void testPatchUnknownBookIs404() {
        try (Response response = client.target(BOOKS + "/999999")
                .request(MediaType.APPLICATION_JSON)
                .method("PATCH", Entity.json("{\"title\":\"Nothing\"}"))) {
            assertEquals(Response.Status.NOT_FOUND.getStatusCode(), response.getStatus());
        }
    }

    // ---------------------------------------------------------------- helpers

    private Long createBook(String title, String author, int year) {
        String json = "{\"title\":\"" + title + "\",\"author\":\"" + author + "\","
                + "\"publish-year\":" + year + ",\"category_id\":10001}";

        try (Response response = target(BOOKS).post(Entity.json(json))) {
            assertEquals(Response.Status.CREATED.getStatusCode(), response.getStatus());

            Map<String, Object> created = response.readEntity(
                    new GenericType<Map<String, Object>>() {
                    });
            assertNotNull("POST should answer with the created book, including its id",
                    created.get("id"));
            return Long.valueOf(created.get("id").toString());
        }
    }

    private Map<String, Object> getBook(Long id) {
        try (Response response = target(BOOKS + "/" + id).get()) {
            assertEquals(Response.Status.OK.getStatusCode(), response.getStatus());
            return response.readEntity(new GenericType<Map<String, Object>>() {
            });
        }
    }

    private void deleteBook(Long id) {
        try (Response response = target(BOOKS + "/" + id).delete()) {
            // 200 or 204 are both fine here
            assertTrue(response.getStatus() < 300);
        }
    }
}
